# Generated by Django 2.0.5 on 2018-05-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepInfo',
            fields=[
                ('depId', models.AutoField(primary_key=True, serialize=False)),
                ('depName', models.CharField(max_length=30)),
                ('depLoc', models.CharField(max_length=30)),
            ],
        ),
    ]
