# Generated by Django 2.0.5 on 2018-06-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_auto_20180607_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloginfo',
            old_name='mark',
            new_name='content',
        ),
    ]
