# Generated by Django 2.0.5 on 2018-06-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAcc',
            fields=[
                ('acId', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=30)),
                ('registerTime', models.DateTimeField()),
                ('mark', models.TextField(blank=True)),
                ('accPic', models.ImageField(blank=True, upload_to='accPic')),
                ('gender', models.BooleanField()),
                ('birthday', models.DateTimeField(blank=True)),
            ],
        ),
    ]
