# Generated by Django 2.0.5 on 2018-06-07 02:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_auto_20180607_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogacc',
            name='registerTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期'),
        ),
    ]
