# Generated by Django 2.0.5 on 2018-06-07 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0003_auto_20180607_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogacc',
            name='registerTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
