# Generated by Django 2.0.5 on 2018-06-20 02:31

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('idcManager', '0002_auto_20180619_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nane', models.CharField(max_length=128, verbose_name='图片名称')),
                ('image', models.ImageField(storage=system.storage.ImageStorage(), upload_to='')),
            ],
        ),
    ]
