# Generated by Django 2.0.5 on 2018-06-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcManager', '0003_imagedesc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagedesc',
            old_name='nane',
            new_name='name',
        ),
    ]
