# Generated by Django 2.0.5 on 2018-06-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idcManager', '0004_auto_20180620_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagedesc',
            options={'verbose_name': '图片管理', 'verbose_name_plural': '图片管理'},
        ),
    ]
