# Generated by Django 2.0.5 on 2018-05-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('bcid', models.AutoField(primary_key=True, serialize=False)),
                ('bcname', models.CharField(max_length=30)),
            ],
        ),
    ]
