# Generated by Django 2.0.5 on 2018-06-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogacc',
            name='gender',
        ),
        migrations.AlterField(
            model_name='blogacc',
            name='accPic',
            field=models.ImageField(null=True, upload_to='accPic'),
        ),
        migrations.AlterField(
            model_name='blogacc',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='blogacc',
            name='mark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogacc',
            name='registerTime',
            field=models.DateTimeField(null=True),
        ),
    ]
